/**
 * P1 catalog: each isolation / OIDC invariant has a test that would fail if the fix is reverted.
 */
export const P1_ITEMS = ["P1.1", "P1.2"] as const;
export type P1Item = (typeof P1_ITEMS)[number];

export interface P1Gate {
  id: string;
  p1: P1Item;
  bug: string;
  before: string;
  after: string;
  evidenceTest: string;
}

export const P1_GATES: P1Gate[] = [
  {
    id: "P1.1-forged-context",
    p1: "P1.1",
    bug: "Plain {tenantId,userKey,role} treated as verified context",
    before: "Caller-built object scoped queries",
    after: "Missing brand is TeamIsolationError",
    evidenceTest: "p1-isolation.test.ts:forged TenantContext without brand is rejected",
  },
  {
    id: "P1.1-no-public-context-factory",
    p1: "P1.1",
    bug: "contextFromMember(arbitrary member) minted a branded TenantContext",
    before: "Public factory stamped any {tenantId,userKey,role}",
    after: "Only bootstrap/resolve after a DB membership row; member objects are not context",
    evidenceTest: "p1-isolation.test.ts:no public factory turns a member object into TenantContext",
  },
  {
    id: "P1.1-caller-tenant-id",
    p1: "P1.1",
    bug: "tenant_id taken from body/input",
    before: "createWorkspace({ tenantId: victim }) wrote into victim",
    after: "Caller tenantId is rejected; SQL uses bound identity from WeakMap",
    evidenceTest: "p1-isolation.test.ts:caller-supplied tenantId on input is rejected",
  },
  {
    id: "P1.1-cross-tenant-read",
    p1: "P1.1",
    bug: "Knowing a workspace UUID reads another tenant",
    before: "getWorkspace(ctxB, idA) returned A's workspace",
    after: "Cross-tenant read is not-found",
    evidenceTest: "p1-isolation.test.ts:cross-tenant read is not-found",
  },
  {
    id: "P1.1-cross-tenant-update",
    p1: "P1.1",
    bug: "Collab write with another tenant's workspace id succeeded",
    before: "updateWorkspaceCollab(ctxB, idA) mutated A",
    after: "Cross-tenant update is not-found and row unchanged",
    evidenceTest: "p1-isolation.test.ts:cross-tenant update is not-found",
  },
  {
    id: "P1.1-cross-tenant-delete",
    p1: "P1.1",
    bug: "deleteWorkspace from another tenant removed the row",
    before: "deleteWorkspace(ctxB, idA) deleted A",
    after: "Cross-tenant delete is not-found; row remains",
    evidenceTest: "p1-isolation.test.ts:cross-tenant delete is not-found",
  },
  {
    id: "P1.1-cross-tenant-fk-member",
    p1: "P1.1",
    bug: "Workspace created_by pointed at a member of another tenant",
    before: "INSERT succeeded across tenants",
    after: "Composite FK rejects cross-tenant created_by",
    evidenceTest: "p1-isolation.test.ts:cross-tenant member FK is rejected",
  },
  {
    id: "P1.1-cross-tenant-fk-workspace",
    p1: "P1.1",
    bug: "Collab row referenced another tenant's workspace id",
    before: "INSERT into collab with mixed tenant/workspace succeeded",
    after: "Composite FK rejects cross-tenant workspace pointer",
    evidenceTest: "p1-isolation.test.ts:cross-tenant workspace FK is rejected",
  },
  {
    id: "P1.1-same-user-two-tenants",
    p1: "P1.1",
    bug: "user_key uniqueness was global so isolation collapsed",
    before: "One membership row for alice across orgs",
    after: "Same user_key in two tenants cannot list the other tenant",
    evidenceTest: "p1-isolation.test.ts:same user_key in two tenants is isolated",
  },
  {
    id: "P1.1-fail-closed-leak",
    p1: "P1.1",
    bug: "Other-tenant id returned 403 with a distinct message",
    before: "Existence leak via error class/message",
    after: "Missing and other-tenant share not-found",
    evidenceTest: "p1-isolation.test.ts:missing and other-tenant are indistinguishable",
  },
  {
    id: "P1.1-bootstrap-not-public",
    p1: "P1.1",
    bug: "Anyone could insert tenant+owner",
    before: "bootstrapTenant({}) created an owner",
    after: "Unlock with configured secret required; empty secret disables",
    evidenceTest: "p1-isolation.test.ts:bootstrap without unlock is denied",
  },
  {
    id: "P1.1-persist-allowlist",
    p1: "P1.1",
    bug: "Raw HAR/JWT/cookie persisted on collab write",
    before: "aRaw and compact JWT stored in report_dto_json",
    after: "assertAllowedCollab rejects capture secrets",
    evidenceTest: "p1-isolation.test.ts:collab write rejects raw capture secrets",
  },
  {
    id: "P1.1-persist-strict-schema",
    p1: "P1.1",
    bug: "Heuristic walk allowed api_key, sessionSecret, unknown nested fields, HTTP dumps",
    before: "Forbidden keys missed underscore variants; extra fields stored",
    after: "Strict ReportDTO/policy schema; unknown fields, HTTP smuggling, oversize Base64 rejected",
    evidenceTest: "p1-isolation.test.ts:collab persist rejects smuggled secrets and unknown fields",
  },
  {
    id: "P1.1-persist-redacted-dto",
    p1: "P1.1",
    bug: "Guard rejected a genuine deep-redacted ReportDTO (replays.raw / Bearer [redacted])",
    before: "toReportDTO(analyze(demo)) could not be stored",
    after: "Engine ReportDTO is re-redacted into a new object and persisted",
    evidenceTest: "p1-isolation.test.ts:deep-redacted ReportDTO from the solo engine is persistable",
  },
  {
    id: "P1.1-persist-read-sanitize",
    p1: "P1.1",
    bug: "Tampered report_dto_json returned to the caller",
    before: "getCollab trusted stored JSON",
    after: "Read path re-validates schema and redaction; tamper is PersistError",
    evidenceTest: "p1-isolation.test.ts:tampered collab row is rejected on read",
  },
  {
    id: "P1.1-collab-upsert-atomic",
    p1: "P1.1",
    bug: "Two first-writes raced to INSERT and one 23505'd or clobbered the other column",
    before: "SELECT then INSERT/UPDATE",
    after: "INSERT ON CONFLICT DO UPDATE merges columns; one row",
    evidenceTest: "p1-isolation.test.ts:concurrent first collab writes upsert to one row",
  },
  {
    id: "P1.1-migration-atomic",
    p1: "P1.1",
    bug: "Failed 0003 left team_tenant without members table",
    before: "Half-applied kernel schema",
    after: "Failed transaction rolls back all Team DDL",
    evidenceTest: "p1-isolation.test.ts:failed team migration leaves no half-applied tables",
  },
  {
    id: "P1.1-solo-lab-untouched",
    p1: "P1.1",
    bug: "Team kernel imported platform auth or broke lab/solo",
    before: "Auth-on coupling; lab login failed",
    after: "No authMiddleware import; demo BOLA and lab login still work",
    evidenceTest: "p1-solo-lab.test.ts:team sources do not import platform auth",
  },
  {
    id: "P1.1-no-auth-schema-copy",
    p1: "P1.1",
    bug: "0001_auth.sql copied into migrations glob",
    before: "Auth-off product applied Better Auth schema",
    after: "0001_auth.sql stays under migrations/auth/",
    evidenceTest: "p1-solo-lab.test.ts:auth schema stays out of the product glob",
  },
  {
    id: "P1.1-context-frozen-identity",
    p1: "P1.1",
    bug: "Branded TenantContext fields were writable so tenantId could be retargeted",
    before: "alice.context.tenantId = bob listed bob's workspaces",
    after: "Context is frozen; WeakMap identity is the SQL authority",
    evidenceTest: "p1-isolation.test.ts:mutated tenantId on a branded context cannot access another tenant",
  },
  {
    id: "P1.1-symbol-copy-rejected",
    p1: "P1.1",
    bug: "Object.getOwnPropertySymbols copied the brand onto a forged context",
    before: "Copied symbol + victim tenantId passed assertTenantContext",
    after: "Unknown object is missing from WeakMap and is TeamIsolationError",
    evidenceTest: "p1-isolation.test.ts:symbol copied onto a new object is rejected",
  },
  {
    id: "P1.1-revoked-member-context",
    p1: "P1.1",
    bug: "Deleted membership left a minted context usable",
    before: "carol context still listed workspaces after DELETE team_member",
    after: "requireActiveMember re-SELECTs membership and fail-closes",
    evidenceTest: "p1-isolation.test.ts:revoked member context cannot be reused",
  },
  {
    id: "P1.1-bootstrap-actor-registry",
    p1: "P1.1",
    bug: "Copied bootstrap brand unlocked tenant creation",
    before: "Fake {brand, label: operator} called bootstrapTenant",
    after: "BootstrapActor must be in WeakMap; copies are TeamBootstrapError",
    evidenceTest: "p1-isolation.test.ts:copied BootstrapActor cannot unlock tenant creation",
  },
  {
    id: "P1.1-persist-team-projection",
    p1: "P1.1",
    bug: "loot.value and replays.raw/curl stored caller strings",
    before: "curl -u and loot secrets survived re-redact heuristics",
    after: "Team projection always stores [redacted] for loot.value and replay blobs",
    evidenceTest: "p1-isolation.test.ts:team projection strips loot and replay credentials from stored JSON",
  },
  {
    id: "P1.1-persist-credential-canaries",
    p1: "P1.1",
    bug: "curl -u, Basic, Cookie, AWS keys in remaining strings were stored",
    before: "Canary scan missed curl user and AWS access keys",
    after: "Defense-in-depth canaries reject live credentials outside projection holes",
    evidenceTest: "p1-isolation.test.ts:live credential canaries still reject secrets outside the projection holes",
  },
  {
    id: "P1.2-fail-closed-config",
    p1: "P1.2",
    bug: "OIDC ran with missing issuer, allowlist, seal, or endpoints",
    before: "Partial env still redirected to an IdP",
    after: "loadTeamOidcConfig throws; HTTP returns 503",
    evidenceTest: "p1-2-crypto.test.ts:OIDC config fail-closes without allowlist, seal, issuer, or endpoints",
  },
  {
    id: "P1.2-secrets-weakmap",
    p1: "P1.2",
    bug: "client_secret and seal key serialized or logged on the config object",
    before: "JSON.stringify leaked the confidential client secret",
    after: "Secrets live in WeakMap; redacted view is [redacted]",
    evidenceTest: "p1-2-crypto.test.ts:config secrets live in WeakMap and do not serialize",
  },
  {
    id: "P1.2-pkce-s256",
    p1: "P1.2",
    bug: "Authorization request omitted PKCE or used plain challenge",
    before: "code_verifier sent or stored in the clear without S256",
    after: "RFC 7636 S256; state stored as SHA-256",
    evidenceTest: "p1-2-crypto.test.ts:RFC 7636 S256 challenge vector and state is hashed",
  },
  {
    id: "P1.2-user-key",
    p1: "P1.2",
    bug: "iss+sub concatenated or taken from unverified claims as user_key",
    before: "user_key = iss + sub collided across encodings",
    after: "user_key = oidc: + sha256(JSON.stringify([iss, sub]))",
    evidenceTest: "p1-2-crypto.test.ts:user_key is oidc: plus sha256 of JSON [iss, sub]",
  },
  {
    id: "P1.2-ssrf-gate",
    p1: "P1.2",
    bug: "Token/JWKS fetch followed an unallowlisted or private host",
    before: "createRemoteJWKSet or open fetch to 10.0.0.5",
    after: "Closed allowlist + inspectJwksUrl teamMode; private hosts denied before fetch",
    evidenceTest: "p1-2-crypto.test.ts:team outbound gate reuses JWKS SSRF policy",
  },
  {
    id: "P1.2-token-post",
    p1: "P1.2",
    bug: "Token POST followed redirects, sent cookies, or returned access_token",
    before: "fetch default redirect + credentials; extra tokens stored",
    after: "credentials omit, redirect manual, only id_token returned",
    evidenceTest: "p1-2-crypto.test.ts:token POST uses credentials omit, denies redirects, and drops extra tokens",
  },
  {
    id: "P1.2-token-no-log",
    p1: "P1.2",
    bug: "Token exchange errors echoed authorization code or tokens",
    before: "Error message included the code",
    after: "Generic TeamAuthError; no code/token/secret in message",
    evidenceTest: "p1-2-crypto.test.ts:token POST error messages do not include code or tokens",
  },
  {
    id: "P1.2-jwks-local",
    p1: "P1.2",
    bug: "jose createRemoteJWKSet fetched JWKS without the SSRF gate",
    before: "Remote JWK set on every verify; unknown kid looped",
    after: "createLocalJWKSet; TTL cache; unknown kid refetches at most once",
    evidenceTest: "p1-2-crypto.test.ts:JWKS cache hits within TTL and refetches at most once for unknown kid",
  },
  {
    id: "P1.2-id-token",
    p1: "P1.2",
    bug: "ID token accepted none, HS256, wrong aud, nonce, exp, or iss",
    before: "Unsigned or HMAC token became a session",
    after: "RS256/PS256/ES256 + sig/iss/aud/azp/exp/iat/nonce",
    evidenceTest: "p1-2-crypto.test.ts:ID token rejects none, HS256, wrong aud, nonce, exp, and issuer",
  },
  {
    id: "P1.2-pending-sealed",
    p1: "P1.2",
    bug: "OIDC state and code_verifier stored in plaintext and reusable",
    before: "Raw state PK and verifier in team_oidc_pending",
    after: "state_hash PK; AES-GCM verifier; consume is single-use",
    evidenceTest: "p1-2-session.test.ts:pending stores hashed state and encrypted verifier, consume is single-use",
  },
  {
    id: "P1.2-session-hash",
    p1: "P1.2",
    bug: "Raw session token stored and not bound to a tenant",
    before: "token column + nullable tenant_id",
    after: "SHA-256 only; tenant_id NOT NULL; FK to team_member",
    evidenceTest: "p1-2-session.test.ts:opaque session stores only the SHA-256 hash and is tenant-bound",
  },
  {
    id: "P1.2-deleted-member",
    p1: "P1.2",
    bug: "Deleted member kept using a minted session",
    before: "Session load trusted token_hash without membership",
    after: "CASCADE plus requireActiveMember; load returns null",
    evidenceTest: "p1-2-session.test.ts:deleted member cannot use a previously minted session",
  },
  {
    id: "P1.2-rotate-atomic",
    p1: "P1.2",
    bug: "Rotation issued a second row or extended TTL",
    before: "INSERT new session; old token still valid",
    after: "Atomic UPDATE token_hash WHERE old hash; expiry stays 12h from created_at",
    evidenceTest: "p1-2-session.test.ts:session rotation is atomic after 6 hours and keeps the original expiry",
  },
  {
    id: "P1.2-https-slug",
    p1: "P1.2",
    bug: "Login on HTTP or without slug still redirected to the IdP",
    before: "Cookie set on http://; tenant chosen later from JWT",
    after: "HTTP is 400; missing/invalid slug is 404; valid slugs (live or unknown) all 302",
    evidenceTest: "p1-2-session.test.ts:login requires HTTPS and a syntactically valid slug",
  },
  {
    id: "P1.2-no-jit",
    p1: "P1.2",
    bug: "Unknown OIDC subject inserted a team_member row",
    before: "Callback JIT-provisioned the caller as analyst",
    after: "Unknown subject is 404; member count unchanged",
    evidenceTest: "p1-2-session.test.ts:callback mints a tenant-bound session and unknown subjects are not provisioned",
  },
  {
    id: "P1.2-cookie-host",
    p1: "P1.2",
    bug: "Session cookie lacked __Host- / Secure / HttpOnly or set Domain",
    before: "claimforge-team.session without Secure on HTTP",
    after: "__Host-claimforge-team.session Path=/ Secure HttpOnly SameSite=Strict, no Domain",
    evidenceTest: "p1-2-session.test.ts:__Host- session cookie is Secure HttpOnly Path=/ SameSite=Strict without Domain",
  },
  {
    id: "P1.2-migration-atomic",
    p1: "P1.2",
    bug: "Failed 0004 left pending tables without session FK",
    before: "Half-applied OIDC schema",
    after: "Failed transaction rolls back 0004 and keeps 0003",
    evidenceTest: "p1-2-sql.test.ts:failed 0004 transaction leaves no P1.2 tables and keeps 0003",
  },
  {
    id: "P1.2-session-fk",
    p1: "P1.2",
    bug: "Session row without tenant_id or live membership inserted",
    before: "Identity-only session; tenant picked at request time",
    after: "tenant_id NOT NULL and FK (tenant_id, user_key) → team_member",
    evidenceTest: "p1-2-sql.test.ts:session row requires tenant_id and a live membership",
  },
  {
    id: "P1.2-cascade",
    p1: "P1.2",
    bug: "Deleting a member left session rows behind",
    before: "ON DELETE RESTRICT or no FK",
    after: "ON DELETE CASCADE removes team_session",
    evidenceTest: "p1-2-sql.test.ts:deleting a member cascades team_session rows",
  },
  {
    id: "P1.2-neon-one-connection",
    p1: "P1.2",
    bug: "BEGIN on one pool connection and COMMIT on another",
    before: "sql.transaction used independent pool.query calls",
    after: "wrapPgPool checks out one client for BEGIN/queries/COMMIT",
    evidenceTest: "p1-2-sql.test.ts:Neon adapter runs BEGIN, queries, and COMMIT on one checked-out client",
  },
  {
    id: "P1.2-claims-not-tenant",
    p1: "P1.2",
    bug: "ID token tenant_id or role minted TenantContext or switched tenant",
    before: "Callback trusted JWT tenant_id / role claims",
    after: "Slug-bound membership resolver; extra claims ignored",
    evidenceTest: "p1-2-adversarial.test.ts:ID token tenant_id and role claims cannot switch tenant",
  },
  {
    id: "P1.2-slug-not-picker",
    p1: "P1.2",
    bug: "Login slug=other-tenant provisioned or bound a member of acme",
    before: "Callback used token sub to pick any membership",
    after: "Pending slug is the only tenant; missing membership is 404",
    evidenceTest: "p1-2-adversarial.test.ts:login slug cannot bind a member of a different tenant",
  },
  {
    id: "P1.2-replay-state",
    p1: "P1.2",
    bug: "Authorization callback state was reusable",
    before: "Second callback with the same state minted another session",
    after: "DELETE RETURNING removes the row; replay is 401",
    evidenceTest: "p1-2-adversarial.test.ts:consumed OIDC state cannot be replayed",
  },
  {
    id: "P1.2-csrf-logout",
    p1: "P1.2",
    bug: "Cross-origin POST logged the user out",
    before: "Logout accepted any Origin",
    after: "Cross-origin POST is 401 and the session stays live",
    evidenceTest: "p1-2-adversarial.test.ts:cross-origin logout is rejected and session stays live",
  },
  {
    id: "P1.2-no-remote-jwks",
    p1: "P1.2",
    bug: "Team OIDC imported jose createRemoteJWKSet or platform auth",
    before: "Remote JWK set / authMiddleware on Team routes",
    after: "No createRemoteJWKSet, authMiddleware, or requireUserId in Team OIDC",
    evidenceTest: "p1-2-adversarial.test.ts:Team OIDC sources do not import createRemoteJWKSet or platform auth",
  },
  {
    id: "P1.2-0003-untouched",
    p1: "P1.2",
    bug: "P1.2 rewrote 0003_team_isolation.sql",
    before: "Kernel migration gained session tables",
    after: "0004 is additive; 0003 has no OIDC/session tables",
    evidenceTest: "p1-2-adversarial.test.ts:0003 does not define OIDC or session tables",
  },
  {
    id: "P1.2-unconfigured-503",
    p1: "P1.2",
    bug: "Missing OIDC env still started login",
    before: "Empty env redirected to a default IdP",
    after: "HTTP 503 oidc is not configured",
    evidenceTest: "p1-2-adversarial.test.ts:missing OIDC env fail-closes login with 503",
  },
  {
    id: "P1.2-no-slug-oracle",
    p1: "P1.2",
    bug: "Login 302 vs 404 told the caller whether a tenant slug exists",
    before: "GET /login?slug=nope was 404 while a live slug was 302",
    after: "Syntactically valid slugs all 302; membership/tenant fail-closed at callback",
    evidenceTest: "p1-2-adversarial.test.ts:valid unknown slug is indistinguishable from a live tenant at login",
  },
  {
    id: "P1.2-no-spoofed-https",
    p1: "P1.2",
    bug: "X-Forwarded-Proto: https on an HTTP URL issued a session cookie",
    before: "requestIsHttps trusted the header by default",
    after: "Only the request URL protocol counts unless CLAIMFORGE_TEAM_TRUST_PROXY is set",
    evidenceTest: "p1-2-adversarial.test.ts:X-Forwarded-Proto is ignored unless CLAIMFORGE_TEAM_TRUST_PROXY is set",
  },
  {
    id: "P1.2-sub-exact",
    p1: "P1.2",
    bug: "oidcUserKey trimmed sub so 'alice' collided with ' alice '",
    before: "sub.trim() before JSON.stringify([iss, sub])",
    after: "Exact OIDC sub; leading/trailing space is a distinct subject",
    evidenceTest: "p1-2-crypto.test.ts:user_key is oidc: plus sha256 of JSON [iss, sub]",
  },
  {
    id: "P1.2-iat-window",
    p1: "P1.2",
    bug: "ID token iat far in the future or hours old still verified",
    before: "Only exp was checked (plus jose clockTolerance)",
    after: "iat within 30s future skew and 5-minute max age for code-exchanged tokens",
    evidenceTest: "p1-2-crypto.test.ts:ID token rejects future iat and stale iat",
  },
  {
    id: "P1.2-no-store",
    p1: "P1.2",
    bug: "Login/callback/session responses were cacheable",
    before: "302 Location and JSON errors omitted Cache-Control",
    after: "Cache-Control: no-store and Pragma: no-cache; callback Referrer-Policy: no-referrer",
    evidenceTest: "p1-2-session.test.ts:login requires HTTPS and a syntactically valid slug",
  },
  {
    id: "P1.2-rotate-grace",
    p1: "P1.2",
    bug: "Two concurrent rotates CAS-missed and logged one request out",
    before: "Loser of UPDATE token_hash could not load the old token",
    after: "prev_token_hash grace 60s; both requests stay authenticated; TTL not extended",
    evidenceTest: "p1-2-session.test.ts:concurrent rotation does not log out the losing request",
  },
  {
    id: "P1.2-token-audit-action",
    p1: "P1.2",
    bug: "Token POST audit used action jwks-fetch",
    before: "auditWithoutSecrets({ action: 'jwks-fetch' }) on the token endpoint",
    after: "action is token-exchange",
    evidenceTest: "p1-2-crypto.test.ts:token POST audit action is token-exchange not jwks-fetch",
  },
  {
    id: "P1.2-token-size-stream",
    p1: "P1.2",
    bug: "Token response was fully buffered with arrayBuffer before the size check",
    before: "await res.arrayBuffer() then compare byteLength",
    after: "Stream read; stop and cancel as soon as maxBytes is exceeded",
    evidenceTest: "p1-2-crypto.test.ts:token POST stops reading when the body exceeds the size cap",
  },
  {
    id: "P1.2-pending-bound",
    p1: "P1.2",
    bug: "GET /oidc/login with random slugs grew team_oidc_pending without bound; consumed rows stayed forever",
    before: "INSERT on every login; consume only set consumed_at",
    after: "Consume DELETE RETURNING; expired rows swept; table capped at 256 by evicting oldest; valid slugs still all 302",
    evidenceTest: "p1-2-adversarial.test.ts:pending rows are bounded and consumed rows are deleted",
  },
  {
    id: "P1.2-jwks-size-stream",
    p1: "P1.2",
    bug: "JWKS GET was fully buffered with arrayBuffer before the size check",
    before: "await res.arrayBuffer() then compare byteLength",
    after: "Shared readCappedBody stream-reads and cancels as soon as JWKS_MAX_BYTES is exceeded",
    evidenceTest: "p1-2-crypto.test.ts:JWKS fetch stops reading when the body exceeds the size cap",
  },
];

export function gatesFor(p1: P1Item): P1Gate[] {
  return P1_GATES.filter((g) => g.p1 === p1);
}
