/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLabSplatRouteImport } from './routes/api/lab/$'
import { Route as ApiTeamAuditRouteImport } from './routes/api/team/audit'
import { Route as ApiTeamCollabRouteImport } from './routes/api/team/collab'
import { Route as ApiTeamMembersRouteImport } from './routes/api/team/members'
import { Route as ApiTeamSessionRouteImport } from './routes/api/team/session'
import { Route as ApiTeamWorkspacesRouteImport } from './routes/api/team/workspaces'
import { Route as ApiTeamOidcCallbackRouteImport } from './routes/api/team/oidc/callback'
import { Route as ApiTeamOidcLoginRouteImport } from './routes/api/team/oidc/login'
import { Route as ApiTeamOidcLogoutRouteImport } from './routes/api/team/oidc/logout'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabSplatRoute = ApiLabSplatRouteImport.update({
  id: '/api/lab/$',
  path: '/api/lab/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamAuditRoute = ApiTeamAuditRouteImport.update({
  id: '/api/team/audit',
  path: '/api/team/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamCollabRoute = ApiTeamCollabRouteImport.update({
  id: '/api/team/collab',
  path: '/api/team/collab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamMembersRoute = ApiTeamMembersRouteImport.update({
  id: '/api/team/members',
  path: '/api/team/members',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamSessionRoute = ApiTeamSessionRouteImport.update({
  id: '/api/team/session',
  path: '/api/team/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamWorkspacesRoute = ApiTeamWorkspacesRouteImport.update({
  id: '/api/team/workspaces',
  path: '/api/team/workspaces',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamOidcCallbackRoute = ApiTeamOidcCallbackRouteImport.update({
  id: '/api/team/oidc/callback',
  path: '/api/team/oidc/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamOidcLoginRoute = ApiTeamOidcLoginRouteImport.update({
  id: '/api/team/oidc/login',
  path: '/api/team/oidc/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeamOidcLogoutRoute = ApiTeamOidcLogoutRouteImport.update({
  id: '/api/team/oidc/logout',
  path: '/api/team/oidc/logout',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/lab/$': typeof ApiLabSplatRoute
  '/api/team/audit': typeof ApiTeamAuditRoute
  '/api/team/collab': typeof ApiTeamCollabRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/api/team/workspaces': typeof ApiTeamWorkspacesRoute
  '/api/team/oidc/callback': typeof ApiTeamOidcCallbackRoute
  '/api/team/oidc/login': typeof ApiTeamOidcLoginRoute
  '/api/team/oidc/logout': typeof ApiTeamOidcLogoutRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/lab/$': typeof ApiLabSplatRoute
  '/api/team/audit': typeof ApiTeamAuditRoute
  '/api/team/collab': typeof ApiTeamCollabRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/api/team/workspaces': typeof ApiTeamWorkspacesRoute
  '/api/team/oidc/callback': typeof ApiTeamOidcCallbackRoute
  '/api/team/oidc/login': typeof ApiTeamOidcLoginRoute
  '/api/team/oidc/logout': typeof ApiTeamOidcLogoutRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/lab/$': typeof ApiLabSplatRoute
  '/api/team/audit': typeof ApiTeamAuditRoute
  '/api/team/collab': typeof ApiTeamCollabRoute
  '/api/team/members': typeof ApiTeamMembersRoute
  '/api/team/session': typeof ApiTeamSessionRoute
  '/api/team/workspaces': typeof ApiTeamWorkspacesRoute
  '/api/team/oidc/callback': typeof ApiTeamOidcCallbackRoute
  '/api/team/oidc/login': typeof ApiTeamOidcLoginRoute
  '/api/team/oidc/logout': typeof ApiTeamOidcLogoutRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/lab/$'
    | '/api/team/audit'
    | '/api/team/collab'
    | '/api/team/members'
    | '/api/team/session'
    | '/api/team/workspaces'
    | '/api/team/oidc/callback'
    | '/api/team/oidc/login'
    | '/api/team/oidc/logout'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/lab/$'
    | '/api/team/audit'
    | '/api/team/collab'
    | '/api/team/members'
    | '/api/team/session'
    | '/api/team/workspaces'
    | '/api/team/oidc/callback'
    | '/api/team/oidc/login'
    | '/api/team/oidc/logout'
  id:
    | '__root__'
    | '/'
    | '/api/lab/$'
    | '/api/team/audit'
    | '/api/team/collab'
    | '/api/team/members'
    | '/api/team/session'
    | '/api/team/workspaces'
    | '/api/team/oidc/callback'
    | '/api/team/oidc/login'
    | '/api/team/oidc/logout'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLabSplatRoute: typeof ApiLabSplatRoute
  ApiTeamAuditRoute: typeof ApiTeamAuditRoute
  ApiTeamCollabRoute: typeof ApiTeamCollabRoute
  ApiTeamMembersRoute: typeof ApiTeamMembersRoute
  ApiTeamSessionRoute: typeof ApiTeamSessionRoute
  ApiTeamWorkspacesRoute: typeof ApiTeamWorkspacesRoute
  ApiTeamOidcCallbackRoute: typeof ApiTeamOidcCallbackRoute
  ApiTeamOidcLoginRoute: typeof ApiTeamOidcLoginRoute
  ApiTeamOidcLogoutRoute: typeof ApiTeamOidcLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab/$': {
      id: '/api/lab/$'
      path: '/api/lab/$'
      fullPath: '/api/lab/$'
      preLoaderRoute: typeof ApiLabSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/audit': {
      id: '/api/team/audit'
      path: '/api/team/audit'
      fullPath: '/api/team/audit'
      preLoaderRoute: typeof ApiTeamAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/collab': {
      id: '/api/team/collab'
      path: '/api/team/collab'
      fullPath: '/api/team/collab'
      preLoaderRoute: typeof ApiTeamCollabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/members': {
      id: '/api/team/members'
      path: '/api/team/members'
      fullPath: '/api/team/members'
      preLoaderRoute: typeof ApiTeamMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/session': {
      id: '/api/team/session'
      path: '/api/team/session'
      fullPath: '/api/team/session'
      preLoaderRoute: typeof ApiTeamSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/workspaces': {
      id: '/api/team/workspaces'
      path: '/api/team/workspaces'
      fullPath: '/api/team/workspaces'
      preLoaderRoute: typeof ApiTeamWorkspacesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/oidc/callback': {
      id: '/api/team/oidc/callback'
      path: '/api/team/oidc/callback'
      fullPath: '/api/team/oidc/callback'
      preLoaderRoute: typeof ApiTeamOidcCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/oidc/login': {
      id: '/api/team/oidc/login'
      path: '/api/team/oidc/login'
      fullPath: '/api/team/oidc/login'
      preLoaderRoute: typeof ApiTeamOidcLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/team/oidc/logout': {
      id: '/api/team/oidc/logout'
      path: '/api/team/oidc/logout'
      fullPath: '/api/team/oidc/logout'
      preLoaderRoute: typeof ApiTeamOidcLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLabSplatRoute: ApiLabSplatRoute,
  ApiTeamAuditRoute: ApiTeamAuditRoute,
  ApiTeamCollabRoute: ApiTeamCollabRoute,
  ApiTeamMembersRoute: ApiTeamMembersRoute,
  ApiTeamSessionRoute: ApiTeamSessionRoute,
  ApiTeamWorkspacesRoute: ApiTeamWorkspacesRoute,
  ApiTeamOidcCallbackRoute: ApiTeamOidcCallbackRoute,
  ApiTeamOidcLoginRoute: ApiTeamOidcLoginRoute,
  ApiTeamOidcLogoutRoute: ApiTeamOidcLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
